### ISSUE TITLE
Login ok, get DeviceList and device failed

### ISSUE THREAD

**Issue by e-skulk** [TA2k/ioBroker.wmswebcontrol#1]
Hi, 

The adapter instance does a login (log: Login successful), but cannot retrieve the devices (log error: Get DevicesList failed; after that: Get device failed).

My devices are:
4 roller shutter
1 vertical blind

Some objects are correctly written to wmswebcontrol.0:

- devices/<device_id_string>/
   - articleNumber 
   - bootTime
   - bootloaderVersion
   - cloudConnectionStatus = 5
   - containerVersion = 10O
   - ...
   - softwareVersion = 10J
   - type = Wcp
- info/
   - connection = true

What could be the reason?
Shall I lookup some API responses? Do you have a good method to do so?

**Comment by TA2k** [comment]
Wenn du die instance in debug log setzt kannst du mir die log file schicken via privat nachricht
https://forum.iobroker.net/user/tombox

**Comment by e-skulk** [comment]
latest master is working fine. Great job!
