### ISSUE TITLE
Various error messages appear in logfile e.g. "AxiosError: Request failed with status code 403"

### ISSUE THREAD

**Issue by BlackTigga** [TA2k/ioBroker.wmswebcontrol#12]
How it could be solved/fixed?

![Screenshot](https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/f2843fa3-6ad4-4f57-9231-f3139fdd98ff)

Versions:
 - Adapter : 0.0.6
 - Node.js: v18.19.0
 - JS-Controller : 5.0.19
 - Plattform: linux

**Comment by BlackTigga** [comment]
Fehler führt dazu, dass keinerlei Fahrbewegungen über Iobroker durchgeführt werden können.

**Comment by TA2k** [comment]
Bitte mal die GitHub version 0.0.8 testen

**Comment by BlackTigga** [comment]
Fehlermeldung erscheint weiterhin auch mit Version 0.0.8:

![Screenshot](https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/7373c4bc-b1d2-461f-9237-aa3fecc03b8b)


Im heruntergeladenen Log sieht die Fehlermeldung allerdings so aus:

![Screenshot_1](https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/ea8190b9-b408-4554-bb19-e499b0bc0892)

**Comment by TA2k** [comment]
bitte 0.0.9 testen

**Comment by BlackTigga** [comment]
Funktioniert. Super Danke.
