### ISSUE TITLE
Adapter hat Probleme nach Wartungsarbeiten bei Warema

### ISSUE THREAD

**Issue by BlackTigga** [TA2k/ioBroker.wmswebcontrol#14]
Hallo, nach den geplanten Wartungsarbeiten am WMS Webcontrol durch Warema hat der Adapter Probleme.

![image](https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/229cdd58-15f7-4a43-964b-4cebfa7d1a65)

![image](https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/bee2e69d-5914-4739-9dce-6f69b0e01b9e)

Versions:

Adapter : 0.0.6
Node.js: v18.19.0
JS-Controller : 5.0.19
Plattform: linux

**Comment by TA2k** [comment]
Bitte die 0.1.0 verwenden

**Comment by BlackTigga** [comment]
Funktioniert wieder.
Danke!
