### ISSUE TITLE
Verschiede Fehler bei Ansteuerung von Warema Außenjalousien

### ISSUE THREAD

**Issue by BlackTigga** [TA2k/ioBroker.wmswebcontrol#16]
Hallo, es sind mehrere Fehler die dazu führen, dass die Ansteuerung über ioBroker nicht immer zuverlässig läuft. 
Es geht in um die Produktgruppe der Außenjalousien von Warema. 
Screenshot aus Warema App:
![2024-03-22_17h02_33](https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/e8556492-5e55-4863-9603-510b90751a1d)

2. Über Schieberegler in VIS weise ich den Datenpunkten **setting0Convert** und **setting1Convert** entsprechende Werte zu. Grundsätzlich scheint es ein Problem bei Zuweisung einer "0" zu geben, siehe nachfolgendes Video. Es wird dann regelmäßig kein Fahrbefehl ausgeführt.

https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/6d669cad-01a6-4992-b2a5-3c2bc3cf10c0

2.  Immer mal wieder werden bei **setting0Convert** und **setting1Convert** Werte erzeugt, die nicht in den Wertebereich passen und entsprechend werden meine Schieberegler an die Anschläge geschoben.

![2024-03-21_16h25_10](https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/f5f4129c-5436-4c8e-8cac-153e4b30c080)

Danke und Gruß.

**Comment by TA2k** [comment]
Punkt 1 sollte mit 0.1.1 behoben sein

Bei settings0 wird durch 2 geteilt und bei settings1 minus 127
Es ist eher komisch dass 255 übertragen wird

**Comment by BlackTigga** [comment]
Punkt 1 ist mit 0.1.1 behoben.
Werde die nächsten Tage weiter beobachten und Auffälligkeiten hier berichten. Ansonsten schließe ich den Issue hier zeitnah.

**Comment by BlackTigga** [comment]
System läuft derzeitig stabil.
